import React from "react";
import { Button, CalendarPicker, Card, ErrorBlock, Grid, List, ProgressBar, Selector, Steps, Tag, TextArea } from "antd-mobile";
import type { ExperienceBlockRendererProps } from "../block-registry";

const field = (p: ExperienceBlockRendererProps, key: string) => { const v = (p.block.binding as Record<string, unknown> | undefined)?.[key]; return typeof v === "string" && v ? v : undefined; };
const data = (p: ExperienceBlockRendererProps) => { const entityRef = field(p, "entityRef"); return entityRef && p.entityRows?.[entityRef] ? { entityRef, rows: p.entityRows[entityRef] } : undefined; };
const targets = (p: ExperienceBlockRendererProps) => { const v = (p.block.binding as Record<string, unknown> | undefined)?.targets; return Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : []; };
function shell(p: ExperienceBlockRendererProps, testid: string, children: React.ReactNode, title = String(p.block.props?.title ?? "")) { return p.block.props?.surface === "plain" ? <div data-testid={testid}>{title && <strong>{title}</strong>}{children}</div> : <Card title={title || undefined} data-testid={testid}>{children}</Card>; }
function empty(p: ExperienceBlockRendererProps, testid: string, text: string) { return shell(p, testid, <ErrorBlock status="empty" title={text} />); }
type CalendarConfig = { testid: string; secondary: "resourceFieldRef" | "memberFieldRef"; create?: boolean; edit?: boolean };
function calendar(p: ExperienceBlockRendererProps, c: CalendarConfig) { const d = data(p), t = field(p, "titleFieldRef"), start = field(p, "startFieldRef"), end = field(p, "endFieldRef"), status = field(p, "statusFieldRef"), secondary = field(p, c.secondary); const [selected, setSelected] = React.useState<Date>(new Date()); const [visible, setVisible] = React.useState(false); if (!d || !t || !start || !secondary) return empty(p, c.testid, "日历尚未绑定必要字段"); const key = selected.toISOString().slice(0, 10); const rows = d.rows.filter(r => String(r.values[start] ?? "").slice(0, 10) === key); return shell(p, c.testid, <><List mode="card" style={{ margin: 0 }}><List.Item clickable arrowIcon extra={key} onClick={() => setVisible(true)}>选择日期</List.Item></List><CalendarPicker visible={visible} selectionMode="single" value={selected} onClose={() => setVisible(false)} onConfirm={v => { if (v) setSelected(v); setVisible(false); }} /><List>{rows.length ? rows.map(r => <List.Item key={r.id} clickable onClick={() => p.onAction?.("itemSelect", { entityRef: d.entityRef, rowId: r.id })} description={`${String(r.values[secondary] ?? "未分配")} · ${String(r.values[start] ?? "")}${end ? ` - ${String(r.values[end] ?? "")}` : ""}`} extra={status ? <Tag>{String(r.values[status] ?? "")}</Tag> : undefined}>{String(r.values[t] ?? "未命名安排")}</List.Item>) : <ErrorBlock status="empty" title="当前日期没有安排" />}</List>{(c.create || c.edit) && <Grid columns={c.create && c.edit ? 2 : 1} gap={8}>{c.create && <Grid.Item><Button block color="primary" onClick={() => p.onAction?.("createRequest", { entityRef: d.entityRef, date: key })}>新建安排</Button></Grid.Item>}{c.edit && <Grid.Item><Button block onClick={() => p.onAction?.("editRequest", { entityRef: d.entityRef, date: key })}>调整安排</Button></Grid.Item>}</Grid>}</>); }
function agenda(p: ExperienceBlockRendererProps) { const d = data(p), t = field(p, "titleFieldRef"), due = field(p, "dueFieldRef"), status = field(p, "statusFieldRef"), member = field(p, "memberFieldRef"); if (!d || !t || !due) return empty(p, "phone-deadline-agenda", "截止议程尚未绑定必要字段"); const rows = [...d.rows].sort((a, b) => String(a.values[due]).localeCompare(String(b.values[due]))); return shell(p, "phone-deadline-agenda", <List>{rows.length ? rows.map(r => <List.Item key={r.id} clickable onClick={() => p.onAction?.("itemSelect", { entityRef: d.entityRef, rowId: r.id })} description={`${String(r.values[due])}${member ? ` · ${String(r.values[member] ?? "未分配")}` : ""}`} extra={<Tag color={String(r.values[status ?? ""]).toLowerCase() === "done" ? "success" : "warning"}>{String(r.values[status ?? ""] ?? "待处理")}</Tag>}>{String(r.values[t])}</List.Item>) : <ErrorBlock status="empty" title="当前没有截止事项" />}</List>); }
function conflict(p: ExperienceBlockRendererProps) { const d = data(p), t = field(p, "titleFieldRef"), start = field(p, "startFieldRef"), end = field(p, "endFieldRef"), resource = field(p, "resourceFieldRef"); if (!d || !t || !start || !end || !resource) return empty(p, "phone-booking-conflict-panel", "冲突面板尚未绑定时间和资源"); return shell(p, "phone-booking-conflict-panel", d.rows.length ? <List>{d.rows.map(r => <List.Item key={r.id} description={`${String(r.values[resource])} · ${String(r.values[start])} - ${String(r.values[end])}`} extra={<Button size="mini" onClick={() => p.onAction?.("editRequest", { entityRef: d.entityRef, rowId: r.id, operation: "rescheduleBooking", targets: targets(p) })}>改期</Button>}>{String(r.values[t])}</List.Item>)}</List> : <ErrorBlock status="empty" title="当前没有预约冲突" />); }
function heatmap(p: ExperienceBlockRendererProps) { const d = data(p), time = field(p, "timeFieldRef"), capacity = field(p, "capacityFieldRef"), booked = field(p, "bookedFieldRef"); if (!d || !time || !capacity || !booked) return empty(p, "phone-schedule-capacity-heatmap", "容量热力图尚未绑定必要字段"); return shell(p, "phone-schedule-capacity-heatmap", d.rows.length ? <Grid columns={2} gap={8}>{d.rows.map(r => { const c = Number(r.values[capacity] ?? 0), b = Number(r.values[booked] ?? 0), percent = c ? Math.round(b / c * 100) : 0; return <Grid.Item key={r.id}><div onClick={() => p.onAction?.("itemSelect", { entityRef: d.entityRef, rowId: r.id })}><strong>{String(r.values[time])}</strong><ProgressBar percent={Math.min(100, percent)} style={{ margin: "8px 0" }} /><small>{b}/{c}</small></div></Grid.Item>; })}</Grid> : <ErrorBlock status="empty" title="没有容量数据" />); }
function rsvp(p: ExperienceBlockRendererProps) { const d = data(p), title = field(p, "titleFieldRef"), member = field(p, "memberFieldRef"), status = field(p, "statusFieldRef"); if (!d || !title || !member || !status) return empty(p, "phone-event-rsvp-panel", "RSVP 尚未绑定必要字段"); return shell(p, "phone-event-rsvp-panel", <List>{d.rows.length ? d.rows.map(r => <List.Item key={r.id} description={String(r.values[title])} extra={<Button size="mini" color="primary" onClick={() => p.onAction?.("submitRequest", { entityRef: d.entityRef, rowId: r.id, operation: "respondRsvp", targets: targets(p) })}>确认</Button>}>{String(r.values[member])} · {String(r.values[status])}</List.Item>) : <ErrorBlock status="empty" title="还没有参与人" />}</List>); }
function recurrence(p: ExperienceBlockRendererProps) { const d = data(p), freq = field(p, "frequencyFieldRef"), interval = field(p, "intervalFieldRef"), endMode = field(p, "endModeFieldRef"); if (!d || !freq || !interval || !endMode) return empty(p, "phone-recurrence-editor", "重复规则尚未绑定必要字段"); const [frequency, setFrequency] = React.useState("weekly"); const [step, setStep] = React.useState(1); return shell(p, "phone-recurrence-editor", <><Selector columns={3} value={[frequency]} options={[{ label: "每天", value: "daily" }, { label: "每周", value: "weekly" }, { label: "每月", value: "monthly" }]} onChange={v => setFrequency(String(v[0] ?? "weekly"))} /><List><List.Item extra={`${step} 个周期`}>重复间隔</List.Item><List.Item extra={String(p.block.props?.timezone ?? "本地时区")}>时区</List.Item></List><Button block color="primary" onClick={() => p.onAction?.("submitRequest", { entityRef: d.entityRef, operation: "saveRecurrence", frequency, interval: step, targets: targets(p) })}>保存规则</Button></>); }
function wizard(p: ExperienceBlockRendererProps, testid: string, label: string, operation: string) { const d = data(p), title = field(p, "titleFieldRef"), status = field(p, "statusFieldRef"); if (!d || !title || !status) return empty(p, testid, `${label}尚未绑定步骤和状态`); const [current, setCurrent] = React.useState(0); const blocked = d.rows.some(r => ["failed", "blocked", "error"].includes(String(r.values[status]).toLowerCase())); return shell(p, testid, <><Steps current={current}><Steps.Step title="检查" /><Steps.Step title="配置" /><Steps.Step title="确认" /></Steps><List>{d.rows.map((r, i) => <List.Item key={r.id} clickable onClick={() => { setCurrent(Math.min(i, 2)); p.onAction?.("itemSelect", { entityRef: d.entityRef, rowId: r.id }); }} extra={<Tag>{String(r.values[status])}</Tag>}>{String(r.values[title])}</List.Item>)}</List><Button block color="primary" disabled={blocked} onClick={() => p.onAction?.("submitRequest", { entityRef: d.entityRef, operation, targets: targets(p) })}>确认完成</Button></>); }

export function renderCalendarWizardPhoneBlock(p: ExperienceBlockRendererProps): React.ReactNode | undefined {
  switch (p.block.type) {
    case "ResourceBookingCalendar": return calendar(p, { testid: "phone-resource-booking-calendar", secondary: "resourceFieldRef", create: true });
    case "DeadlineAgenda": return agenda(p);
    case "BookingConflictPanel": return conflict(p);
    case "ScheduleCapacityHeatmap": return heatmap(p);
    case "EventRsvpPanel": return rsvp(p);
    case "RecurrenceEditor": return recurrence(p);
    case "DeploymentWizard": return wizard(p, "phone-deployment-wizard", "部署向导", "startDeployment");
    default: return undefined;
  }
}
