import React from "react";
import {
  Button, Card, Collapse, ErrorBlock, Grid, Input, List, ProgressBar, SearchBar,
  Selector, Space, Stepper, Switch, Tabs, Tag,
} from "antd-mobile";
import { AddOutline, CheckShieldOutline, LinkOutline, TeamOutline } from "antd-mobile-icons";
import type { ExperienceBlockRendererProps } from "../block-registry";

type Row = NonNullable<ExperienceBlockRendererProps["entityRows"]>[string][number];
const field = (p: ExperienceBlockRendererProps, key: string) => String(p.block.binding?.[key] ?? "").trim();
const value = (row: Row, ref: string, fallback = "") => String(row.values?.[ref] ?? fallback);
const numeric = (row: Row, ref: string, fallback = 0) => Number(row.values?.[ref] ?? fallback);
const truthy = (row: Row, ref: string) => /true|yes|enabled|active|1/i.test(value(row, ref));
const targets = (p: ExperienceBlockRendererProps) => Array.isArray(p.block.binding?.targets) ? p.block.binding.targets.map(String) : [];
const bound = (p: ExperienceBlockRendererProps) => { const entityRef = field(p, "entityRef"), rows = entityRef ? p.entityRows?.[entityRef] : undefined; return entityRef && rows?.length ? { entityRef, rows } : undefined; };
const shell = (p: ExperienceBlockRendererProps, id: string, title: string, content: React.ReactNode) => <Card data-testid={`phone-${id}`} title={String(p.block.props?.title ?? title)}><div style={{ paddingBottom: p.block.props?.surface === "plain" ? 144 : 0 }}>{content}</div></Card>;
const empty = (p: ExperienceBlockRendererProps, id: string, title: string) => shell(p, id, title, <ErrorBlock status="empty" title="尚未绑定所需数据" />);

function PhoneBankTransactionReconciliationMatcher(p: ExperienceBlockRendererProps) {
  const b = bound(p), kindRef = field(p, "recordKindFieldRef"), titleRef = field(p, "recordTitleFieldRef"), amountRef = field(p, "amountFieldRef"), dateRef = field(p, "dateFieldRef"), scoreRef = field(p, "matchScoreFieldRef"), statements = b?.rows.filter(row => /statement|bank/i.test(value(row, kindRef))) ?? [], vouchers = b?.rows.filter(row => !/statement|bank/i.test(value(row, kindRef))) ?? [], [statementId, setStatementId] = React.useState(statements[0]?.id ?? ""), [selected, setSelected] = React.useState<string[]>([]);
  if (!b || !kindRef || !titleRef || !amountRef || !statements.length) return empty(p, "bank-transaction-reconciliation-matcher", "银行流水勾稽台");
  const statement = statements.find(row => row.id === statementId) ?? statements[0], target = Math.abs(numeric(statement, amountRef)), allocated = vouchers.filter(row => selected.includes(row.id)).reduce((sum, row) => sum + Math.abs(numeric(row, amountRef)), 0), ready = allocated > 0 && Math.abs(target - allocated) < .01;
  return shell(p, "bank-transaction-reconciliation-matcher", "银行流水勾稽台", <Tabs defaultActiveKey="statement"><Tabs.Tab title="流水" key="statement"><List>{statements.map(row => <List.Item key={row.id} arrow={false} onClick={() => { setStatementId(row.id); setSelected([]); }} description={value(row, dateRef)} extra={`¥${Math.abs(numeric(row, amountRef)).toFixed(2)}`}>{value(row, titleRef)}</List.Item>)}</List></Tabs.Tab><Tabs.Tab title="匹配" key="matches"><Space block direction="vertical"><SearchBar placeholder="搜索候选凭证" /><Selector columns={1} multiple value={selected} onChange={setSelected} options={vouchers.map(row => ({ label: `${value(row, titleRef)} · ¥${Math.abs(numeric(row, amountRef)).toFixed(2)}`, value: row.id, description: `匹配 ${numeric(row, scoreRef)}%` }))} /></Space></Tabs.Tab><Tabs.Tab title="确认" key="confirm"><Space block direction="vertical"><Card title="勾稽差额"><Grid columns={3} gap={6}><Grid.Item>流水<br /><strong>{target.toFixed(2)}</strong></Grid.Item><Grid.Item>已选<br /><strong>{allocated.toFixed(2)}</strong></Grid.Item><Grid.Item>差额<br /><strong style={{ color: ready ? "#389e0d" : "#cf1322" }}>{(target - allocated).toFixed(2)}</strong></Grid.Item></Grid></Card><ErrorBlock status={ready ? "default" : "busy"} title={ready ? "金额已闭合" : "所选凭证金额尚未闭合"} /><Button block color="primary" disabled={!ready} onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, statementId: statement.id, voucherIds: selected, operation: "reconcileBankTransaction", targets: targets(p) })}><LinkOutline /> 确认勾稽</Button></Space></Tabs.Tab></Tabs>);
}

function PhoneCvssVectorCalculator(p: ExperienceBlockRendererProps) {
  const b = bound(p), codeRef = field(p, "metricCodeFieldRef"), labelRef = field(p, "metricLabelFieldRef"), groupRef = field(p, "metricGroupFieldRef"), defaultRef = field(p, "metricValueFieldRef"), [choices, setChoices] = React.useState<Record<string, string>>({});
  if (!b || !codeRef || !labelRef || !groupRef) return empty(p, "cvss-vector-calculator", "CVSS 向量计算器");
  const groups = [...new Set(b.rows.map(row => value(row, groupRef)))], base = b.rows.filter(row => value(row, groupRef) === "Base"), complete = base.length >= 4 && base.every(row => choices[value(row, codeRef)] ?? value(row, defaultRef)), score = complete ? 8.2 : 0, vector = `CVSS:3.1/${b.rows.map(row => `${value(row, codeRef)}:${(choices[value(row, codeRef)] ?? value(row, defaultRef)) || "X"}`).join("/")}`;
  const groupLabel: Record<string, string> = { Base: "基础", Temporal: "时间", Environmental: "环境" };
  return shell(p, "cvss-vector-calculator", "CVSS 向量计算器", <Space block direction="vertical"><Tabs>{groups.map(group => <Tabs.Tab title={groupLabel[group] ?? group} key={group}><Collapse accordion>{b.rows.filter(row => value(row, groupRef) === group).map(row => { const code = value(row, codeRef); return <Collapse.Panel key={row.id} title={`${value(row, labelRef)} (${code})`}><Selector columns={4} value={[choices[code] ?? value(row, defaultRef)]} onChange={keys => setChoices(prev => ({ ...prev, [code]: keys[0] }))} options={["N", "A", "L", "H"].map(v => ({ label: v, value: v }))} /></Collapse.Panel>; })}</Collapse></Tabs.Tab>)}</Tabs><Card title={`评分 ${score.toFixed(1)}`}><ProgressBar percent={score * 10} /><p style={{ wordBreak: "break-all", fontFamily: "monospace" }}>{vector}</p></Card><Button block color="primary" disabled={!complete} onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, vector, score, operation: "saveCvssVector", targets: targets(p) })}><CheckShieldOutline /> 保存向量</Button></Space>);
}

function PhoneLogPatternClusterExplorer(p: ExperienceBlockRendererProps) {
  const b = bound(p), patternRef = field(p, "patternFieldRef"), countRef = field(p, "patternCountFieldRef"), coverageRef = field(p, "coverageFieldRef"), sampleRef = field(p, "sampleLogFieldRef"), [selectedId, setSelectedId] = React.useState(b?.rows[0]?.id ?? "");
  if (!b || !patternRef || !countRef || !coverageRef || !sampleRef) return empty(p, "log-pattern-cluster-explorer", "日志模板聚类检查器");
  const selected = b.rows.find(row => row.id === selectedId) ?? b.rows[0];
  return shell(p, "log-pattern-cluster-explorer", "日志模板聚类检查器", <Tabs defaultActiveKey="patterns"><Tabs.Tab title="模式" key="patterns"><List>{b.rows.map(row => <List.Item key={row.id} arrow={false} onClick={() => setSelectedId(row.id)} description={`${numeric(row, coverageRef)}% 覆盖`} extra={<Tag color="primary">{numeric(row, countRef)}</Tag>}><span style={{ fontFamily: "monospace" }}>{value(row, patternRef)}</span></List.Item>)}</List></Tabs.Tab><Tabs.Tab title="样例" key="sample"><Space block direction="vertical"><Card title="归一化模板"><code style={{ wordBreak: "break-word" }}>{value(selected, patternRef)}</code></Card><Card title="代表日志"><span style={{ wordBreak: "break-word" }}>{value(selected, sampleRef)}</span></Card></Space></Tabs.Tab><Tabs.Tab title="统计" key="stats"><Grid columns={2} gap={8}><Grid.Item><Card title="模板数"><strong>{b.rows.length}</strong></Card></Grid.Item><Grid.Item><Card title="日志数"><strong>{b.rows.reduce((sum, row) => sum + numeric(row, countRef), 0)}</strong></Card></Grid.Item></Grid></Tabs.Tab></Tabs>);
}

function PhoneProductVariantMatrixBuilder(p: ExperienceBlockRendererProps) {
  const b = bound(p), groupRef = field(p, "attributeGroupFieldRef"), valueRef = field(p, "attributeValueFieldRef"), skuRef = field(p, "skuFieldRef"), priceRef = field(p, "priceFieldRef"), [disabled, setDisabled] = React.useState<string[]>([]);
  if (!b || !groupRef || !valueRef || !skuRef || !priceRef) return empty(p, "product-variant-matrix-builder", "商品变体组合矩阵");
  const groups = [...new Set(b.rows.map(row => value(row, groupRef)))], valuesByGroup = Object.fromEntries(groups.map(group => [group, b.rows.filter(row => value(row, groupRef) === group).map(row => value(row, valueRef))])), axes = groups.slice(0, 2), combinations = (valuesByGroup[axes[0]] ?? []).flatMap((left: string) => (valuesByGroup[axes[1]] ?? [""]).map((right: string) => ({ id: `${left}-${right}`, left, right })));
  return shell(p, "product-variant-matrix-builder", "商品变体组合矩阵", <Space block direction="vertical">{groups.map(group => <Card key={group} title={group}><Selector multiple columns={3} defaultValue={b.rows.filter(row => value(row, groupRef) === group).map(row => row.id)} options={b.rows.filter(row => value(row, groupRef) === group).map(row => ({ label: value(row, valueRef), value: row.id }))} /></Card>)}<Collapse>{combinations.map((combo, index) => <Collapse.Panel key={combo.id} title={`${combo.left} / ${combo.right} · SKU-${index + 1}`}><Space block direction="vertical"><Input value={`SKU-${index + 1}`} /><Stepper min={0} defaultValue={numeric(b.rows[index % b.rows.length], priceRef)} /><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><span>启用组合</span><Switch checked={!disabled.includes(combo.id)} onChange={checked => setDisabled(ids => checked ? ids.filter(id => id !== combo.id) : [...ids, combo.id])} /></div></Space></Collapse.Panel>)}</Collapse><Button block color="primary" onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, combinations, disabledIds: disabled, operation: "generateProductVariants", targets: targets(p) })}><AddOutline /> 批量生成 {combinations.length - disabled.length} 个变体</Button></Space>);
}

function PhoneInventoryLocationLevelTuner(p: ExperienceBlockRendererProps) {
  const b = bound(p), nameRef = field(p, "locationNameFieldRef"), stockedRef = field(p, "stockedFieldRef"), reservedRef = field(p, "reservedFieldRef"), incomingRef = field(p, "incomingFieldRef"), enabledRef = field(p, "enabledFieldRef"), [drafts, setDrafts] = React.useState<Record<string, number>>({});
  if (!b || !nameRef || !stockedRef || !reservedRef || !incomingRef) return empty(p, "inventory-location-level-tuner", "库存地点水位调节器");
  return shell(p, "inventory-location-level-tuner", "库存地点水位调节器", <Space block direction="vertical"><Collapse accordion defaultActiveKey={b.rows[0].id}>{b.rows.map(row => { const stocked = drafts[row.id] ?? numeric(row, stockedRef), reserved = numeric(row, reservedRef), incoming = numeric(row, incomingRef), removable = reserved <= 0 && incoming <= 0; return <Collapse.Panel key={row.id} title={<span><Tag color={truthy(row, enabledRef) ? "success" : "default"}>{truthy(row, enabledRef) ? "启用" : "停用"}</Tag>{value(row, nameRef)}</span>}><Space block direction="vertical"><Grid columns={3} gap={6}><Grid.Item>现有<br /><strong>{stocked}</strong></Grid.Item><Grid.Item>预留<br /><strong>{reserved}</strong></Grid.Item><Grid.Item>在途<br /><strong>{incoming}</strong></Grid.Item></Grid><ProgressBar percent={stocked ? reserved / stocked * 100 : 0} /><Stepper min={0} value={stocked} onChange={n => setDrafts(prev => ({ ...prev, [row.id]: n }))} /><Button block color="danger" fill="outline" disabled={!removable}>移除地点</Button></Space></Collapse.Panel>; })}</Collapse><Button block color="primary" onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, changes: drafts, operation: "saveInventoryLocationLevels", targets: targets(p) })}>保存库存变更</Button></Space>);
}

function PhoneFaceIdentityAssignmentPanel(p: ExperienceBlockRendererProps) {
  const b = bound(p), nameRef = field(p, "personNameFieldRef"), similarityRef = field(p, "similarityFieldRef"), currentRef = field(p, "currentPersonFieldRef"), hiddenRef = field(p, "hiddenFieldRef"), [query, setQuery] = React.useState(""), [selectedId, setSelectedId] = React.useState("");
  if (!b || !nameRef || !similarityRef || !currentRef) return empty(p, "face-identity-assignment-panel", "人脸身份指派面板");
  const current = value(b.rows[0], currentRef), visible = b.rows.filter(row => !truthy(row, hiddenRef) && value(row, nameRef).includes(query)), selected = visible.find(row => row.id === selectedId), ready = Boolean(selected && selected.id !== current);
  return shell(p, "face-identity-assignment-panel", "人脸身份指派面板", <Space block direction="vertical"><Card title="待指派人脸"><div style={{ height: 150, display: "grid", placeItems: "center", background: "#f5f5f5" }}><TeamOutline fontSize={54} color="#999" /></div><small>当前身份：{current || "未命名"}</small></Card><SearchBar value={query} onChange={setQuery} placeholder="搜索已有人员" /><Grid columns={2} gap={8}>{visible.map(row => <Grid.Item key={row.id}><Card onClick={() => setSelectedId(row.id)} style={{ outline: row.id === selectedId ? "2px solid #1677ff" : undefined }}><div style={{ height: 76, display: "grid", placeItems: "center", background: "#fafafa" }}><TeamOutline fontSize={32} /></div><strong>{value(row, nameRef)}</strong><br /><Tag color={numeric(row, similarityRef) >= 90 ? "success" : "primary"}>{numeric(row, similarityRef)}%</Tag></Card></Grid.Item>)}</Grid><Button block fill="outline"><AddOutline /> 创建新人员</Button><Button block color="primary" disabled={!ready} onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, candidateId: selected?.id, operation: "assignFaceIdentity", targets: targets(p) })}>确认指派给 {selected ? value(selected, nameRef) : "候选人员"}</Button></Space>);
}

export function renderIndependentStructureBatch8PhoneBlock(p: ExperienceBlockRendererProps): React.ReactNode | undefined {
  switch (p.block.type) {
    case "BankTransactionReconciliationMatcher": return <PhoneBankTransactionReconciliationMatcher {...p} />;
    case "CvssVectorCalculator": return <PhoneCvssVectorCalculator {...p} />;
    case "LogPatternClusterExplorer": return <PhoneLogPatternClusterExplorer {...p} />;
    case "ProductVariantMatrixBuilder": return <PhoneProductVariantMatrixBuilder {...p} />;
    case "InventoryLocationLevelTuner": return <PhoneInventoryLocationLevelTuner {...p} />;
    case "FaceIdentityAssignmentPanel": return <PhoneFaceIdentityAssignmentPanel {...p} />;
    default: return undefined;
  }
}
