import React from "react";
import { Button, CalendarPicker, Card, ErrorBlock, Grid, List, Popup, ProgressBar, Space, Tag } from "antd-mobile";
import type { ExperienceBlockRendererProps } from "../block-registry";

type Row = NonNullable<ExperienceBlockRendererProps["entityRows"]>[string][number];
const ref=(p:ExperienceBlockRendererProps,key:string)=>{const v=(p.block.binding as Record<string,unknown>|undefined)?.[key];return typeof v==="string"&&v?v:undefined};
const bound=(p:ExperienceBlockRendererProps)=>{const entityRef=ref(p,"entityRef"),rows=entityRef?p.entityRows?.[entityRef]:undefined;return entityRef&&rows?{entityRef,rows}:undefined};
const targets=(p:ExperienceBlockRendererProps)=>{const v=(p.block.binding as Record<string,unknown>|undefined)?.targets;return Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[]};
function shell(p:ExperienceBlockRendererProps,testid:string,children:React.ReactNode){const title=String(p.block.props?.title??"");return p.block.props?.surface==="plain"?<section data-testid={testid}>{title&&<strong>{title}</strong>}{children}</section>:<Card title={title||undefined} data-testid={testid}>{children}</Card>}
const missing=(p:ExperienceBlockRendererProps,testid:string,text:string)=>shell(p,testid,<ErrorBlock status="empty" title={text}/>);
type Config={testid:string;secondary:"memberFieldRef"|"resourceFieldRef";extra?:"participantFieldRef"|"locationFieldRef"|"typeFieldRef";create?:boolean;edit?:boolean};
function calendar(p:ExperienceBlockRendererProps,c:Config){const d=bound(p),title=ref(p,"titleFieldRef"),start=ref(p,"startFieldRef"),end=ref(p,"endFieldRef"),status=ref(p,"statusFieldRef"),secondary=ref(p,c.secondary),extra=c.extra?ref(p,c.extra):undefined,[selected,setSelected]=React.useState(new Date()),[visible,setVisible]=React.useState(false);if(!d||!title||!start||!secondary)return missing(p,c.testid,"排期尚未绑定必要字段");const key=selected.toISOString().slice(0,10),rows=d.rows.filter(row=>{const from=String(row.values[start]??"").slice(0,10),to=end?String(row.values[end]??from).slice(0,10):from;return from<=key&&key<=to});return shell(p,c.testid,<><List mode="card" style={{margin:0}}><List.Item clickable arrowIcon extra={key} onClick={()=>setVisible(true)}>选择日期</List.Item></List><CalendarPicker visible={visible} selectionMode="single" value={selected} onClose={()=>setVisible(false)} onConfirm={v=>{if(v)setSelected(v);setVisible(false)}}/><List>{rows.length?rows.map(row=><List.Item key={row.id} clickable onClick={()=>p.onAction?.("itemSelect",{entityRef:d.entityRef,rowId:row.id})} description={`${String(row.values[secondary]??"未分配")}${extra?` · ${String(row.values[extra]??"")}`:""} · ${String(row.values[start]??"")}${end?` - ${String(row.values[end]??"")}`:""}`} extra={status?<Tag>{String(row.values[status]??"")}</Tag>:undefined}>{String(row.values[title]??"未命名安排")}</List.Item>):<ErrorBlock status="empty" title="当前日期没有安排"/>}</List>{(c.create||c.edit)&&<Grid columns={c.create&&c.edit?2:1} gap={8}>{c.create&&<Grid.Item><Button block color="primary" onClick={()=>p.onAction?.("createRequest",{entityRef:d.entityRef,date:key})}>新建</Button></Grid.Item>}{c.edit&&<Grid.Item><Button block onClick={()=>p.onAction?.("editRequest",{entityRef:d.entityRef,date:key})}>调整</Button></Grid.Item>}</Grid>}</>)}
function waitlist(p:ExperienceBlockRendererProps){const d=bound(p),title=ref(p,"titleFieldRef"),member=ref(p,"memberFieldRef"),position=ref(p,"positionFieldRef"),status=ref(p,"statusFieldRef");if(!d||!title||!member||!position||!status)return missing(p,"phone-appointment-waitlist-panel","候补队列尚未绑定必要字段");const rows=[...d.rows].sort((a,b)=>Number(a.values[position])-Number(b.values[position]));return shell(p,"phone-appointment-waitlist-panel",rows.length?<List>{rows.map(row=><List.Item key={row.id} description={String(row.values[title])} extra={<Button size="mini" color="primary" disabled={String(row.values[status]).toLowerCase()!=="waiting"} onClick={()=>p.onAction?.("submitRequest",{entityRef:d.entityRef,rowId:row.id,operation:"confirmWaitlistSeat",targets:targets(p)})}>确认</Button>}>#{String(row.values[position])} {String(row.values[member])}</List.Item>)}</List>:<ErrorBlock status="empty" title="当前没有候补预约"/>)}
function overridePanel(p:ExperienceBlockRendererProps){const d=bound(p),date=ref(p,"dateFieldRef"),start=ref(p,"startTimeFieldRef"),end=ref(p,"endTimeFieldRef"),enabled=ref(p,"enabledFieldRef"),timezone=ref(p,"timezoneFieldRef");if(!d||!date||!start||!end||!enabled)return missing(p,"phone-availability-override-panel","覆盖规则尚未绑定日期和窗口");return shell(p,"phone-availability-override-panel",<List>{d.rows.length?d.rows.map(row=><List.Item key={row.id} clickable onClick={()=>p.onAction?.("editRequest",{entityRef:d.entityRef,rowId:row.id})} description={`${String(row.values[start])} - ${String(row.values[end])}${timezone?` · ${String(row.values[timezone]??"")}`:""}`} extra={<Button size="mini" color="primary" onClick={()=>p.onAction?.("submitRequest",{entityRef:d.entityRef,rowId:row.id,operation:"saveAvailabilityOverride",targets:targets(p)})}>保存</Button>}>{String(row.values[date])} · {String(row.values[enabled]).toLowerCase()==="false"?"不可用":"可用"}</List.Item>):<ErrorBlock status="empty" title="还没有日期覆盖"/>}</List>)}
function overlap(p:ExperienceBlockRendererProps){const d=bound(p),member=ref(p,"memberFieldRef"),timezone=ref(p,"timezoneFieldRef"),start=ref(p,"startTimeFieldRef"),end=ref(p,"endTimeFieldRef");if(!d||!member||!timezone||!start||!end)return missing(p,"phone-timezone-overlap-panel","时区重叠尚未绑定必要字段");return shell(p,"phone-timezone-overlap-panel",d.rows.length?<List>{d.rows.map(row=><List.Item key={row.id} clickable onClick={()=>p.onAction?.("itemSelect",{entityRef:d.entityRef,rowId:row.id})} description={`${String(row.values[start])} - ${String(row.values[end])}`} extra={<Tag color="primary">{String(row.values[timezone])}</Tag>}>{String(row.values[member])}</List.Item>)}</List>:<ErrorBlock status="empty" title="没有共同可用窗口"/>)}
function publishBar(p:ExperienceBlockRendererProps){const d=bound(p),status=ref(p,"statusFieldRef"),dirty=ref(p,"dirtyFieldRef"),published=ref(p,"publishedAtFieldRef"),row=d?.rows[0];if(!d||!status||!dirty||!row)return missing(p,"phone-schedule-publish-bar","发布栏尚未绑定状态和变更字段");const state=String(row.values[status]).toLowerCase(),changed=[true,"true","dirty","changed"].includes(row.values[dirty] as never),publishing=["publishing","saving"].includes(state);return shell(p,"phone-schedule-publish-bar",<><List><List.Item description={published?`最近发布：${String(row.values[published]??"-")}`:undefined}>{changed?"有未保存变更":state==="published"?"已发布":"草稿"}</List.Item></List><Grid columns={2} gap={8}><Grid.Item><Button block disabled={!changed||publishing} onClick={()=>p.onAction?.("actionTrigger",{entityRef:d.entityRef,rowId:row.id,operation:"saveSchedule",targets:targets(p)})}>保存</Button></Grid.Item><Grid.Item><Button block color="primary" loading={publishing} disabled={changed||publishing} onClick={()=>p.onAction?.("submitRequest",{entityRef:d.entityRef,rowId:row.id,operation:"publishSchedule",targets:targets(p)})}>发布</Button></Grid.Item></Grid></>)}
function reschedule(p:ExperienceBlockRendererProps){const d=bound(p),title=ref(p,"titleFieldRef"),start=ref(p,"startFieldRef"),requested=ref(p,"requestedStartFieldRef"),status=ref(p,"statusFieldRef"),reason=ref(p,"reasonFieldRef"),[open,setOpen]=React.useState(false),[active,setActive]=React.useState<Row>();if(!d||!title||!start||!requested||!status)return missing(p,"phone-reschedule-request-drawer","改期请求尚未绑定必要字段");const rows=d.rows.filter(row=>["pending","requested","waiting"].includes(String(row.values[status]).toLowerCase()));return shell(p,"phone-reschedule-request-drawer",<><Button block onClick={()=>setOpen(true)}>查看改期请求 {rows.length}</Button><Popup visible={open} onMaskClick={()=>setOpen(false)} bodyStyle={{padding:12,maxHeight:"75vh",overflow:"auto"}}><strong>改期请求</strong><List>{rows.length?rows.map(row=><List.Item key={row.id} clickable onClick={()=>{setActive(row);p.onAction?.("itemSelect",{entityRef:d.entityRef,rowId:row.id})}} description={`${String(row.values[start])} → ${String(row.values[requested])}${reason?` · ${String(row.values[reason]??"")}`:""}`}>{String(row.values[title])}</List.Item>):<ErrorBlock status="empty" title="当前没有待处理改期"/>}</List>{active&&<Grid columns={2} gap={8}><Grid.Item><Button block color="danger" onClick={()=>p.onAction?.("submitRequest",{entityRef:d.entityRef,rowId:active.id,operation:"rejectReschedule",targets:targets(p)})}>拒绝</Button></Grid.Item><Grid.Item><Button block color="primary" onClick={()=>p.onAction?.("submitRequest",{entityRef:d.entityRef,rowId:active.id,operation:"acceptReschedule",targets:targets(p)})}>接受</Button></Grid.Item></Grid>}</Popup></>)}

export function renderScheduleStatusPhoneBlock(p:ExperienceBlockRendererProps):React.ReactNode|undefined{switch(p.block.type){
case"OnCallScheduleCalendar":return calendar(p,{testid:"phone-on-call-schedule-calendar",secondary:"memberFieldRef",extra:"typeFieldRef",edit:true});
case"AppointmentWaitlistPanel":return waitlist(p);case"AvailabilityOverridePanel":return overridePanel(p);case"TimezoneOverlapPanel":return overlap(p);case"SchedulePublishBar":return publishBar(p);case"RescheduleRequestDrawer":return reschedule(p);default:return undefined}}
