import React from "react";
import { Button, Card, Checkbox, Dialog, ErrorBlock, List, ProgressBar, Selector, Space, Steps, Tag, TextArea } from "antd-mobile";
import type { ExperienceBlockRendererProps } from "../block-registry";
import { DATA_GOVERNANCE_LABELS } from "../data-governance-blocks";

const text = (value: unknown, fallback = "") => String(value ?? "").trim() || fallback;
const ref = (props: ExperienceBlockRendererProps, key: string) => text(props.block.binding?.[key]);
const targets = (props: ExperienceBlockRendererProps) => Array.isArray(props.block.binding?.targets) ? props.block.binding.targets.map(String) : [];
const failed = (value: unknown) => /failed|error|invalid|conflict|失败|错误|冲突/i.test(text(value));

export function renderDataGovernancePhoneBlock(props: ExperienceBlockRendererProps): React.ReactNode | undefined {
  const label = DATA_GOVERNANCE_LABELS[props.block.type]; if (!label) return undefined;
  const entityRef = ref(props, "entityRef"), rows = entityRef ? props.entityRows?.[entityRef] : undefined;
  const titleRef = ref(props, "titleFieldRef"), sourceRef = ref(props, "sourceFieldRef"), targetRef = ref(props, "targetFieldRef"), statusRef = ref(props, "statusFieldRef"), messageRef = ref(props, "messageFieldRef"), valueRef = ref(props, "valueFieldRef"), parentRef = ref(props, "parentFieldRef"), timeRef = ref(props, "timeFieldRef"), oldRef = ref(props, "oldValueFieldRef"), newRef = ref(props, "newValueFieldRef"), allowedRef = ref(props, "allowedFieldRef");
  const [draft, setDraft] = React.useState(""), [selected, setSelected] = React.useState<string[]>([]);
  const shell = (children: React.ReactNode) => props.block.props?.surface === "plain" ? <section data-testid={`phone-${props.block.type}`}>{children}</section> : <Card title={text(props.block.props?.title, label)} data-testid={`phone-${props.block.type}`}>{children}</Card>;
  if (!entityRef || !rows) return shell(<ErrorBlock status="empty" title={`${label}尚未绑定实体`} />);
  const submit = (operation: string, payload: Record<string, unknown> = {}) => props.onAction?.("submitRequest", { entityRef, operation, targets: targets(props), ...payload });
  const failures = rows.filter(row => failed(row.values?.[statusRef]));
  let body: React.ReactNode;
  switch (props.block.type) {
    case "SchemaMappingPanel": body = <Space direction="vertical" block><List>{rows.map(row => <List.Item key={row.id} description={`${text(row.values?.[sourceRef], row.id)} → ${text(row.values?.[targetRef], "未映射")}`} extra={<Tag color={failed(row.values?.[statusRef]) ? "danger" : "success"}>{text(row.values?.[statusRef], "待校验")}</Tag>}>{text(row.values?.[titleRef], "字段映射")}</List.Item>)}</List><Button block onClick={() => submit("validateSchemaMapping", { rowIds: rows.map(row => row.id) })}>校验映射</Button><Button block color="primary" disabled={failures.length > 0} onClick={() => submit("saveSchemaMapping", { rowIds: rows.map(row => row.id) })}>提交映射</Button></Space>; break;
    case "FieldTransformPanel": { const row = rows[0]; body = row ? <Space direction="vertical" block><TextArea value={draft} onChange={setDraft} placeholder="填写转换表达式" autoSize={{ minRows: 3, maxRows: 6 }} /><List><List.Item description={text(row.values?.[sourceRef], "-")}>输入</List.Item><List.Item description={text(row.values?.[valueRef], "尚未预览")}>预览</List.Item></List><Button block onClick={() => submit("previewFieldTransform", { rowId: row.id, expression: draft })}>预览</Button><Button block color="primary" disabled={!draft} onClick={() => submit("saveFieldTransform", { rowId: row.id, expression: draft })}>保存转换</Button></Space> : <ErrorBlock status="empty" title="暂无转换字段" />; break; }
    case "ImportValidationPanel": body = <Space direction="vertical" block><ErrorBlock status={failures.length ? "default" : "empty"} title={failures.length ? `${failures.length} 个错误阻止导入` : "校验通过"} /><List>{rows.map(row => <List.Item key={row.id} description={text(row.values?.[messageRef])}>{text(row.values?.[titleRef], row.id)}</List.Item>)}</List><Button block color="primary" disabled={failures.length > 0} onClick={() => submit("startValidatedImport", { rowIds: rows.map(row => row.id) })}>开始导入</Button></Space>; break;
    case "DuplicateResolutionPanel": body = <Space direction="vertical" block><Selector columns={1} value={selected} onChange={setSelected} options={rows.map(row => ({ value: row.id, label: `${text(row.values?.[parentRef], "重复组")} · ${text(row.values?.[titleRef], row.id)}` }))} /><Button block color="primary" disabled={!selected.length} onClick={() => submit("resolveDuplicates", { winnerIds: selected })}>提交去重方案</Button></Space>; break;
    case "MergePreviewPanel": body = <Space direction="vertical" block><List>{rows.map(row => <List.Item key={row.id} description={text(row.values?.[valueRef], "-")}>{text(row.values?.[titleRef], row.id)}</List.Item>)}</List><small>当前仅为合并预览，尚未写入。</small><Button block color="primary" onClick={async () => { if (await Dialog.confirm({ content: "确认按当前预览提交合并请求？" })) submit("confirmMerge", { rowIds: rows.map(row => row.id) }); }}>确认合并</Button></Space>; break;
    case "SyncCheckpointPanel": body = <List>{[...rows].sort((a, b) => text(b.values?.[timeRef]).localeCompare(text(a.values?.[timeRef]))).map((row, index) => <List.Item key={row.id} description={`${text(row.values?.[timeRef])} · ${text(row.values?.[statusRef])}`} extra={<Button size="mini" disabled={index !== 0 || failed(row.values?.[statusRef])} onClick={() => submit("resumeFromCheckpoint", { rowId: row.id })}>继续</Button>}>{text(row.values?.[titleRef], row.id)}</List.Item>)}</List>; break;
    case "RetryQueuePanel": body = <Space direction="vertical" block><ErrorBlock status={failures.length ? "default" : "empty"} title={failures.length ? `${failures.length} 个失败项可重试` : "没有失败项"} /><List>{rows.map(row => <List.Item key={row.id} extra={<Tag color={failed(row.values?.[statusRef]) ? "danger" : "success"}>{text(row.values?.[statusRef])}</Tag>}>{text(row.values?.[titleRef], row.id)}</List.Item>)}</List><Button block disabled={!failures.length} onClick={() => submit("retryFailedItems", { rowIds: failures.map(row => row.id) })}>仅重试失败项</Button></Space>; break;
    case "JobRunHistoryPanel": body = <Steps direction="vertical">{[...rows].sort((a, b) => text(b.values?.[timeRef]).localeCompare(text(a.values?.[timeRef]))).map(row => <Steps.Step key={row.id} title={text(row.values?.[titleRef], row.id)} description={`${text(row.values?.[statusRef])} · ${text(row.values?.[timeRef])}`} />)}</Steps>; break;
    case "DataLineagePanel": body = <List>{rows.filter(row => !text(row.values?.[parentRef])).map(row => <List.Item key={row.id} clickable onClick={() => props.onAction?.("itemSelect", { entityRef, rowId: row.id })} description={`${rows.filter(child => text(child.values?.[parentRef]) === row.id).length} 个下游节点`}>{text(row.values?.[titleRef], row.id)}</List.Item>)}</List>; break;
    case "RecordChangePreview": body = <Space direction="vertical" block><List>{rows.map(row => <List.Item key={row.id} description={`${text(row.values?.[oldRef], "-")} → ${text(row.values?.[newRef], "-")}`}>{text(row.values?.[titleRef], row.id)}</List.Item>)}</List><small>变更预览尚未写入。</small><Button block color="primary" onClick={() => submit("confirmRecordChanges", { rowIds: rows.map(row => row.id) })}>提交变更请求</Button></Space>; break;
    case "PermissionMatrixPanel": body = <Space direction="vertical" block><Checkbox.Group value={selected} onChange={values => setSelected(values.map(String))}>{rows.map(row => <Checkbox key={row.id} value={row.id} block>{text(row.values?.[titleRef], row.id)} · {text(row.values?.[allowedRef], "继承")}</Checkbox>)}</Checkbox.Group><small>保存只提交权限申请，不在前端直接提权。</small><Button block color="primary" disabled={!selected.length} onClick={() => submit("requestPermissionMatrixChange", { rowIds: selected })}>提交权限申请</Button></Space>; break;
    case "WebhookDeliveryPanel": body = <Space direction="vertical" block><ProgressBar percent={rows.length ? Math.round(((rows.length - failures.length) / rows.length) * 100) : 0} /><List>{rows.map(row => <List.Item key={row.id} description={text(row.values?.[messageRef])} extra={failed(row.values?.[statusRef]) ? <Button size="mini" onClick={() => submit("retryWebhookDelivery", { rowIds: [row.id] })}>重试</Button> : <Tag color="success">成功</Tag>}>{text(row.values?.[titleRef], row.id)}</List.Item>)}</List><Button block disabled={!failures.length} onClick={() => submit("retryWebhookDelivery", { rowIds: failures.map(row => row.id) })}>重试全部失败项</Button></Space>; break;
    default: return undefined;
  }
  return shell(body);
}
