import React from "react";
import {
  Alert, Badge, Button, Card, Checkbox, Collapse, Descriptions, Empty, Flex, Input,
  InputNumber, List, Progress, Radio, Segmented, Space, Statistic, Switch, Tag, Typography,
} from "antd";
import {
  CheckCircleOutlined, LinkOutlined, PlusOutlined, SafetyCertificateOutlined,
  SearchOutlined, TeamOutlined,
} from "@ant-design/icons";
import type { ExperienceBlockRenderer, ExperienceBlockRendererProps } from "./block-registry";

type Row = NonNullable<ExperienceBlockRendererProps["entityRows"]>[string][number];
const field = (p: ExperienceBlockRendererProps, key: string) => String(p.block.binding?.[key] ?? "").trim();
const value = (row: Row, ref: string, fallback = "") => String(row.values?.[ref] ?? fallback);
const numeric = (row: Row, ref: string, fallback = 0) => Number(row.values?.[ref] ?? fallback);
const truthy = (row: Row, ref: string) => /true|yes|enabled|active|1/i.test(value(row, ref));
const targets = (p: ExperienceBlockRendererProps) => Array.isArray(p.block.binding?.targets) ? p.block.binding.targets.map(String) : [];
const bound = (p: ExperienceBlockRendererProps) => { const entityRef = field(p, "entityRef"), rows = entityRef ? p.entityRows?.[entityRef] : undefined; return entityRef && rows?.length ? { entityRef, rows } : undefined; };
const shell = (p: ExperienceBlockRendererProps, id: string, title: string, children: React.ReactNode) => p.block.props?.surface === "plain" ? <section data-testid={id} style={{ paddingBottom: 120 }}>{children}</section> : <Card size="small" title={String(p.block.props?.title ?? title)} data-testid={id}>{children}</Card>;
const missing = (p: ExperienceBlockRendererProps, id: string, title: string) => shell(p, id, title, <Empty description="区块尚未绑定所需数据" />);

export const reconciliationCanConfirm = (selectedAmount: number, targetAmount: number) => selectedAmount > 0 && Math.abs(selectedAmount - targetAmount) < 0.01;
export const cvssBaseComplete = (metrics: string[]) => metrics.length >= 4 && metrics.every(Boolean);
export const patternCoverageValid = (coverage: number) => Number.isFinite(coverage) && coverage >= 0 && coverage <= 100;
export const variantDraftValid = (skus: string[]) => skus.length > 0 && skus.every(Boolean) && new Set(skus).size === skus.length;
export const inventoryLocationCanRemove = (reserved: number, incoming: number) => reserved <= 0 && incoming <= 0;
export const faceCandidateCanAssign = (currentPersonId: string, candidatePersonId: string) => Boolean(candidatePersonId) && currentPersonId !== candidatePersonId;

export const BankTransactionReconciliationMatcherRenderer: ExperienceBlockRenderer = p => {
  const b = bound(p), kindRef = field(p, "recordKindFieldRef"), titleRef = field(p, "recordTitleFieldRef"), amountRef = field(p, "amountFieldRef"), dateRef = field(p, "dateFieldRef"), scoreRef = field(p, "matchScoreFieldRef");
  const statements = b?.rows.filter(row => /statement|bank/i.test(value(row, kindRef))) ?? [], vouchers = b?.rows.filter(row => !/statement|bank/i.test(value(row, kindRef))) ?? [];
  const [statementId, setStatementId] = React.useState(statements[0]?.id ?? ""), [selected, setSelected] = React.useState<string[]>([]);
  if (!b || !kindRef || !titleRef || !amountRef || !dateRef || !statements.length) return missing(p, "bank-transaction-reconciliation-matcher", "银行流水勾稽台");
  const statement = statements.find(row => row.id === statementId) ?? statements[0], target = Math.abs(numeric(statement, amountRef)), selectedAmount = vouchers.filter(row => selected.includes(row.id)).reduce((sum, row) => sum + Math.abs(numeric(row, amountRef)), 0), difference = target - selectedAmount;
  return shell(p, "bank-transaction-reconciliation-matcher", "银行流水勾稽台", <Flex vertical gap={12}><Flex justify="space-between" align="center" wrap gap={8}><Segmented options={["未对账", "已匹配", "已完成"]} defaultValue="未对账" /><Input prefix={<SearchOutlined />} placeholder="搜索流水或凭证" style={{ width: 220, maxWidth: "100%" }} /></Flex><div style={{ display: "grid", gridTemplateColumns: "minmax(180px,.8fr) minmax(0,1.2fr)", gap: 12 }}><Card size="small" title="银行流水轨道"><List dataSource={statements} renderItem={row => <List.Item onClick={() => { setStatementId(row.id); setSelected([]); }} style={{ cursor: "pointer", paddingInline: 8, background: row.id === statement.id ? "#e6f4ff" : undefined }}><List.Item.Meta title={value(row, titleRef)} description={`${value(row, dateRef)} · ¥${numeric(row, amountRef).toFixed(2)}`} /></List.Item>} /></Card><Card size="small" title="候选凭证" extra={<Badge count={selected.length} showZero />}><Space direction="vertical" size={8} style={{ width: "100%" }}>{vouchers.map(row => <Card key={row.id} size="small" styles={{ body: { padding: 9 } }}><Flex align="center" gap={8} wrap><Checkbox checked={selected.includes(row.id)} onChange={event => setSelected(ids => event.target.checked ? [...ids, row.id] : ids.filter(id => id !== row.id))} /><div style={{ flex: 1, minWidth: 110 }}><Typography.Text strong ellipsis>{value(row, titleRef)}</Typography.Text><br /><Typography.Text type="secondary">{value(row, dateRef)}</Typography.Text></div><Tag color={numeric(row, scoreRef) >= 90 ? "success" : "blue"}>{numeric(row, scoreRef)}%</Tag><Typography.Text>{Math.abs(numeric(row, amountRef)).toFixed(2)}</Typography.Text></Flex></Card>)}</Space></Card></div><Card size="small"><Flex justify="space-between" align="center" wrap gap={10}><Space size="large" wrap><Statistic title="流水金额" value={target} precision={2} /><Statistic title="已选金额" value={selectedAmount} precision={2} /><Statistic title="待分配差额" value={difference} precision={2} valueStyle={{ color: Math.abs(difference) < .01 ? "#3f8600" : "#cf1322" }} /></Space><Button type="primary" icon={<LinkOutlined />} disabled={!reconciliationCanConfirm(selectedAmount, target)} onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, statementId: statement.id, voucherIds: selected, operation: "reconcileBankTransaction", targets: targets(p) })}>确认勾稽</Button></Flex></Card></Flex>);
};

const CVSS_OPTIONS: Record<string, string[]> = { AV: ["N", "A", "L", "P"], AC: ["L", "H"], PR: ["N", "L", "H"], UI: ["N", "R"] };
export const CvssVectorCalculatorRenderer: ExperienceBlockRenderer = p => {
  const b = bound(p), codeRef = field(p, "metricCodeFieldRef"), labelRef = field(p, "metricLabelFieldRef"), groupRef = field(p, "metricGroupFieldRef"), defaultRef = field(p, "metricValueFieldRef"), [group, setGroup] = React.useState("Base"), [choices, setChoices] = React.useState<Record<string, string>>({});
  if (!b || !codeRef || !labelRef || !groupRef) return missing(p, "cvss-vector-calculator", "CVSS 向量计算器");
  const rows = b.rows.filter(row => value(row, groupRef, "Base") === group), selected = (code: string, row: Row) => choices[code] ?? value(row, defaultRef), baseValues = b.rows.filter(row => value(row, groupRef) === "Base").map(row => selected(value(row, codeRef), row)), complete = cvssBaseComplete(baseValues), score = complete ? Math.min(10, 3.1 + baseValues.filter(v => /N|L|H/.test(v)).length * 1.35) : 0, vector = `CVSS:3.1/${b.rows.map(row => `${value(row, codeRef)}:${selected(value(row, codeRef), row) || "X"}`).join("/")}`;
  return shell(p, "cvss-vector-calculator", "CVSS 向量计算器", <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) 260px", gap: 16 }}><Flex vertical gap={14}><Segmented block value={group} onChange={v => setGroup(String(v))} options={["Base", "Temporal", "Environmental"]} />{rows.map(row => { const code = value(row, codeRef); return <Flex key={row.id} justify="space-between" align="center" gap={12}><div><Typography.Text strong>{value(row, labelRef)}</Typography.Text><br /><Typography.Text code>{code}</Typography.Text></div><Radio.Group optionType="button" buttonStyle="solid" value={selected(code, row)} onChange={event => setChoices(prev => ({ ...prev, [code]: event.target.value }))} options={(CVSS_OPTIONS[code] ?? ["X", "L", "H"]).map(v => ({ label: v, value: v }))} /></Flex>; })}</Flex><Card size="small" title="实时评分"><Progress type="circle" percent={score * 10} format={() => score.toFixed(1)} strokeColor={score >= 7 ? "#ff4d4f" : "#faad14"} /><Typography.Title level={5}>{score >= 7 ? "高危" : complete ? "中危" : "待完成"}</Typography.Title><Typography.Paragraph code copyable style={{ wordBreak: "break-all" }}>{vector}</Typography.Paragraph><Alert type={complete ? "success" : "warning"} showIcon message={complete ? "基础向量完整" : "请完成全部基础指标"} /><Button block type="primary" icon={<SafetyCertificateOutlined />} disabled={!complete} style={{ marginTop: 12 }} onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, vector, score, operation: "saveCvssVector", targets: targets(p) })}>保存向量</Button></Card></div>);
};

export const LogPatternClusterExplorerRenderer: ExperienceBlockRenderer = p => {
  const b = bound(p), patternRef = field(p, "patternFieldRef"), countRef = field(p, "patternCountFieldRef"), coverageRef = field(p, "coverageFieldRef"), sampleRef = field(p, "sampleLogFieldRef"), [selectedId, setSelectedId] = React.useState(b?.rows[0]?.id ?? "");
  if (!b || !patternRef || !countRef || !coverageRef || !sampleRef) return missing(p, "log-pattern-cluster-explorer", "日志模板聚类检查器");
  const selected = b.rows.find(row => row.id === selectedId) ?? b.rows[0], total = b.rows.reduce((sum, row) => sum + numeric(row, countRef), 0), coverage = b.rows.reduce((sum, row) => sum + numeric(row, coverageRef), 0);
  return shell(p, "log-pattern-cluster-explorer", "日志模板聚类检查器", <Flex vertical gap={12}><Flex gap={12}><Card size="small"><Statistic title="分析日志" value={total} /></Card><Card size="small"><Statistic title="模板数" value={b.rows.length} /></Card><Card size="small"><Statistic title="覆盖率" value={coverage} suffix="%" /></Card></Flex><div style={{ display: "grid", gridTemplateColumns: "minmax(250px,.75fr) minmax(0,1.25fr)", gap: 12 }}><Card size="small" title="模式簇"><List dataSource={b.rows} renderItem={row => <List.Item onClick={() => setSelectedId(row.id)} style={{ cursor: "pointer", paddingInline: 10, background: row.id === selected.id ? "#f0f5ff" : undefined }} extra={<Badge count={numeric(row, countRef)} overflowCount={99999} />}><Typography.Text ellipsis>{value(row, patternRef)}</Typography.Text></List.Item>} /></Card><Flex vertical gap={12}><Card size="small" title="归一化模板"><Typography.Paragraph code copyable>{value(selected, patternRef)}</Typography.Paragraph><Progress percent={numeric(selected, coverageRef)} /></Card><Card size="small" title="代表样例"><Typography.Paragraph style={{ fontFamily: "monospace", wordBreak: "break-word" }}>{value(selected, sampleRef)}</Typography.Paragraph><Tag color="processing">该样例属于当前模板</Tag></Card></Flex></div>{!patternCoverageValid(coverage) && <Alert type="error" showIcon message="聚类覆盖率超出有效范围" />}</Flex>);
};

export const ProductVariantMatrixBuilderRenderer: ExperienceBlockRenderer = p => {
  const b = bound(p), groupRef = field(p, "attributeGroupFieldRef"), valueRef = field(p, "attributeValueFieldRef"), skuRef = field(p, "skuFieldRef"), priceRef = field(p, "priceFieldRef"), enabledRef = field(p, "enabledFieldRef"), [enabled, setEnabled] = React.useState<Record<string, boolean>>({}), [draftSkus, setDraftSkus] = React.useState<Record<string, string>>({});
  if (!b || !groupRef || !valueRef || !skuRef || !priceRef) return missing(p, "product-variant-matrix-builder", "商品变体组合矩阵");
  const groups = [...new Set(b.rows.map(row => value(row, groupRef)))], valuesByGroup = Object.fromEntries(groups.map(group => [group, b.rows.filter(row => value(row, groupRef) === group).map(row => value(row, valueRef))])), axes = groups.slice(0, 2), combinations = (valuesByGroup[axes[0]] ?? []).flatMap((left: string) => (valuesByGroup[axes[1]] ?? [""]).map((right: string) => ({ id: `${left}-${right}`, left, right }))), defaultSku = (id: string) => `SKU-${combinations.findIndex(c => c.id === id) + 1}`, skus = combinations.filter(c => enabled[c.id] ?? true).map(c => draftSkus[c.id] ?? defaultSku(c.id)), valid = variantDraftValid(skus);
  return shell(p, "product-variant-matrix-builder", "商品变体组合矩阵", <Flex vertical gap={14}><Flex gap={12} wrap>{groups.map(group => <Card key={group} size="small" title={group} style={{ flex: "1 1 220px" }}><Space wrap>{valuesByGroup[group].map((item: string) => <Tag key={item} color="blue" closable>{item}</Tag>)}</Space><Button type="dashed" size="small" icon={<PlusOutlined />} style={{ marginTop: 10 }}>添加属性值</Button></Card>)}</Flex><div style={{ display: "grid", gridTemplateColumns: `72px repeat(${Math.max(1, valuesByGroup[axes[1]]?.length ?? 1)}, minmax(0,1fr))`, gap: 6 }}><div /><>{(valuesByGroup[axes[1]] ?? ["组合"]).map((item: string) => <Typography.Text key={item} strong style={{ textAlign: "center" }}>{item}</Typography.Text>)}</>{(valuesByGroup[axes[0]] ?? []).map((left: string) => <React.Fragment key={left}><Typography.Text strong>{left}</Typography.Text>{combinations.filter(c => c.left === left).map((c, index) => { const on = enabled[c.id] ?? true; return <Card key={c.id} size="small" styles={{ body: { padding: 7, opacity: on ? 1 : .55, minWidth: 0 } }}><Flex justify="space-between" align="center" gap={4}><Typography.Text ellipsis style={{ fontSize: 12 }}>{c.left}/{c.right}</Typography.Text><Switch size="small" checked={on} onChange={checked => setEnabled(prev => ({ ...prev, [c.id]: checked }))} /></Flex><Input size="small" value={draftSkus[c.id] ?? defaultSku(c.id)} onChange={event => setDraftSkus(prev => ({ ...prev, [c.id]: event.target.value }))} style={{ marginTop: 7, minWidth: 0 }} /><InputNumber size="small" prefix="¥" defaultValue={numeric(b.rows[index % b.rows.length], priceRef)} style={{ width: "100%", marginTop: 5 }} /></Card>; })}</React.Fragment>)}</div><Flex justify="space-between" align="center" wrap gap={8}><Alert type={valid ? "success" : "error"} showIcon message={valid ? `将生成 ${skus.length} 个唯一变体` : "存在空 SKU 或重复 SKU"} /><Button type="primary" disabled={!valid} onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, combinations, skus, operation: "generateProductVariants", targets: targets(p) })}>批量生成变体</Button></Flex></Flex>);
};

export const InventoryLocationLevelTunerRenderer: ExperienceBlockRenderer = p => {
  const b = bound(p), nameRef = field(p, "locationNameFieldRef"), stockedRef = field(p, "stockedFieldRef"), reservedRef = field(p, "reservedFieldRef"), incomingRef = field(p, "incomingFieldRef"), enabledRef = field(p, "enabledFieldRef"), [drafts, setDrafts] = React.useState<Record<string, number>>({}), [activeId, setActiveId] = React.useState(b?.rows[0]?.id ?? "");
  if (!b || !nameRef || !stockedRef || !reservedRef || !incomingRef) return missing(p, "inventory-location-level-tuner", "库存地点水位调节器");
  const active = b.rows.find(row => row.id === activeId) ?? b.rows[0], stocked = drafts[active.id] ?? numeric(active, stockedRef), reserved = numeric(active, reservedRef), incoming = numeric(active, incomingRef), available = Math.max(0, stocked - reserved);
  return shell(p, "inventory-location-level-tuner", "库存地点水位调节器", <div style={{ display: "grid", gridTemplateColumns: "220px minmax(0,1fr)", gap: 12 }}><Card size="small" title="库存地点"><List dataSource={b.rows} renderItem={row => <List.Item onClick={() => setActiveId(row.id)} style={{ cursor: "pointer", paddingInline: 10, background: row.id === active.id ? "#e6f4ff" : undefined }} extra={<Badge status={truthy(row, enabledRef) ? "success" : "default"} />}>{value(row, nameRef)}</List.Item>} /></Card><Flex vertical gap={12}><Card size="small" title={value(active, nameRef)} extra={<Switch defaultChecked={truthy(active, enabledRef)} />}><Flex gap={10} wrap>{[{ label: "现有", n: stocked, color: "#1677ff" }, { label: "预留", n: reserved, color: "#fa8c16" }, { label: "在途", n: incoming, color: "#722ed1" }, { label: "可用", n: available, color: "#52c41a" }].map(item => <div key={item.label} style={{ flex: 1, minWidth: 110, padding: 12, borderTop: `4px solid ${item.color}`, background: "#fafafa" }}><Typography.Text type="secondary">{item.label}</Typography.Text><Typography.Title level={4} style={{ margin: 0 }}>{item.n}</Typography.Title></div>)}</Flex><Progress percent={Math.min(100, stocked ? reserved / stocked * 100 : 0)} strokeColor="#fa8c16" format={percent => `预留 ${Math.round(percent ?? 0)}%`} /><Flex align="center" gap={8} style={{ marginTop: 14 }}><Typography.Text>库存草稿</Typography.Text><InputNumber min={0} value={stocked} onChange={n => setDrafts(prev => ({ ...prev, [active.id]: Number(n ?? 0) }))} /></Flex></Card><Alert type={inventoryLocationCanRemove(reserved, incoming) ? "info" : "warning"} showIcon message={inventoryLocationCanRemove(reserved, incoming) ? "该地点可以安全移除" : "存在预留或在途库存，禁止移除地点"} /><Flex justify="end" gap={8}><Button danger disabled={!inventoryLocationCanRemove(reserved, incoming)}>移除地点</Button><Button type="primary" onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, changes: drafts, operation: "saveInventoryLocationLevels", targets: targets(p) })}>保存变更</Button></Flex></Flex></div>);
};

export const FaceIdentityAssignmentPanelRenderer: ExperienceBlockRenderer = p => {
  const b = bound(p), nameRef = field(p, "personNameFieldRef"), imageRef = field(p, "faceImageFieldRef"), similarityRef = field(p, "similarityFieldRef"), currentRef = field(p, "currentPersonFieldRef"), hiddenRef = field(p, "hiddenFieldRef"), [selectedId, setSelectedId] = React.useState(""), [query, setQuery] = React.useState("");
  if (!b || !nameRef || !imageRef || !similarityRef || !currentRef) return missing(p, "face-identity-assignment-panel", "人脸身份指派面板");
  const currentId = value(b.rows[0], currentRef), visible = b.rows.filter(row => !truthy(row, hiddenRef) && value(row, nameRef).includes(query)), selected = visible.find(row => row.id === selectedId);
  return shell(p, "face-identity-assignment-panel", "人脸身份指派面板", <Flex vertical gap={12}><div style={{ display: "grid", gridTemplateColumns: "170px minmax(0,1fr)", gap: 12 }}><Card size="small" title="待指派人脸"><div style={{ aspectRatio: "1", borderRadius: 6, background: "#f0f2f5", display: "grid", placeItems: "center", overflow: "hidden" }}><img src={value(b.rows[0], imageRef)} alt="待指派人脸" style={{ width: "100%", height: "100%", objectFit: "cover" }} onError={event => { event.currentTarget.style.display = "none"; }} /><TeamOutlined style={{ position: "absolute", fontSize: 48, color: "#bfbfbf", zIndex: -1 }} /></div><Descriptions size="small" column={1} items={[{ key: "current", label: "当前身份", children: currentId || "未命名" }, { key: "faces", label: "关联照片", children: 18 }]} /></Card><Card size="small" title="相似人员候选" extra={<Button size="small" icon={<PlusOutlined />}>创建新人</Button>}><Input prefix={<SearchOutlined />} value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索已有人员" style={{ marginBottom: 12 }} /><div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 8 }}>{visible.map(row => <Card key={row.id} hoverable onClick={() => setSelectedId(row.id)} styles={{ body: { padding: 7, outline: row.id === selectedId ? "2px solid #1677ff" : undefined, minWidth: 0 } }} cover={<div style={{ height: 72, background: "#f5f5f5", display: "grid", placeItems: "center" }}><TeamOutlined style={{ fontSize: 28, color: "#8c8c8c" }} /></div>}><Flex vertical gap={4}><Typography.Text strong ellipsis>{value(row, nameRef)}</Typography.Text><Tag color={numeric(row, similarityRef) >= 90 ? "success" : "blue"}>{numeric(row, similarityRef)}%</Tag></Flex></Card>)}</div></Card></div><Flex justify="space-between" align="center" wrap gap={8}><Alert type={selected && faceCandidateCanAssign(currentId, selected.id) ? "success" : "info"} showIcon message={selected ? `准备指派给 ${value(selected, nameRef)}` : "请选择已有人员，或创建新人员"} /><Button type="primary" icon={<CheckCircleOutlined />} disabled={!selected || !faceCandidateCanAssign(currentId, selected.id)} onClick={() => p.onAction?.("submitRequest", { entityRef: b.entityRef, candidateId: selected?.id, operation: "assignFaceIdentity", targets: targets(p) })}>确认指派</Button></Flex></Flex>);
};

export const INDEPENDENT_STRUCTURE_BATCH8_LABELS: Record<string, string> = {
  BankTransactionReconciliationMatcher: "银行流水勾稽台",
  CvssVectorCalculator: "CVSS 向量计算器",
  LogPatternClusterExplorer: "日志模板聚类检查器",
  ProductVariantMatrixBuilder: "商品变体组合矩阵",
  InventoryLocationLevelTuner: "库存地点水位调节器",
  FaceIdentityAssignmentPanel: "人脸身份指派面板",
};
