import React from "react";
import { Alert, Badge, Button, Card, Collapse, Descriptions, Empty, Flex, Input, InputNumber, List, Progress, Segmented, Select, Slider, Space, Statistic, Steps, Switch, Tabs, Tag, Timeline, Transfer, Tree, Typography } from "antd";
import { CaretRightOutlined, ClockCircleOutlined, PlayCircleOutlined, ReloadOutlined, SaveOutlined, SendOutlined } from "@ant-design/icons";
import type { ExperienceBlockRenderer, ExperienceBlockRendererProps } from "./block-registry";

type Row = NonNullable<ExperienceBlockRendererProps["entityRows"]>[string][number];
const field=(p:ExperienceBlockRendererProps,k:string)=>String(p.block.binding?.[k]??"").trim();
const value=(r:Row,f:string,d="")=>String(r.values?.[f]??d);
const numeric=(r:Row,f:string,d=0)=>Number(r.values?.[f]??d);
const targets=(p:ExperienceBlockRendererProps)=>Array.isArray(p.block.binding?.targets)?p.block.binding.targets.map(String):[];
const bound=(p:ExperienceBlockRendererProps)=>{const entityRef=field(p,"entityRef"),rows=entityRef?p.entityRows?.[entityRef]:undefined;return entityRef&&rows?.length?{entityRef,rows}:undefined};
const shell=(p:ExperienceBlockRendererProps,id:string,title:string,children:React.ReactNode)=>p.block.props?.surface==="plain"?<section data-testid={id} style={{paddingBottom:120}}>{children}</section>:<Card size="small" title={String(p.block.props?.title??title)} data-testid={id}>{children}</Card>;
const missing=(p:ExperienceBlockRendererProps,id:string,title:string)=>shell(p,id,title,<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="区块尚未绑定所需数据"/>);

export const compositeRoleCanSave=(assigned:string[],selfId:string)=>assigned.length>0&&!assigned.includes(selfId);
export const httpRequestCanSend=(method:string,url:string)=>Boolean(method&&/^https?:\/\//i.test(url.trim()));
export const bomCanSave=(quantities:number[])=>quantities.length>0&&quantities.every(v=>Number.isFinite(v)&&v>0);
export const thresholdsValid=(warning:number,critical:number)=>Number.isFinite(warning)&&Number.isFinite(critical)&&warning<critical;
export const trimRangeValid=(start:number,end:number,duration:number)=>start>=0&&end>start&&end<=duration;
export const cronExpressionValid=(expression:string)=>expression.trim().split(/\s+/).length===5;

export const CompositeRoleBuilderRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),name=field(p,"roleNameFieldRef"),scope=field(p,"roleScopeFieldRef"),assignedRef=field(p,"assignedFieldRef"),inherited=field(p,"inheritedFieldRef"),selfId=String(p.block.props?.roleId??"current-role"),[assigned,setAssigned]=React.useState<string[]>(b?.rows.filter(r=>/true|yes|assigned|direct/i.test(value(r,assignedRef))).map(r=>r.id)??[]);if(!b||!name||!scope||!assignedRef)return missing(p,"composite-role-builder","复合角色构建器");const effective=b.rows.filter(r=>assigned.includes(r.id)||/true|yes|inherited/i.test(value(r,inherited))),valid=compositeRoleCanSave(assigned,selfId);return shell(p,"composite-role-builder","复合角色构建器",<Flex vertical gap={10}><Alert type={valid?"info":"error"} showIcon message={valid?`直接角色 ${assigned.length} 个，有效角色 ${effective.length} 个`:"复合角色不能包含自身且至少选择一个角色"}/><Transfer dataSource={b.rows.map(r=>({key:r.id,title:value(r,name),description:value(r,scope)}))} targetKeys={assigned} onChange={keys=>setAssigned(keys.map(String))} titles={["可用角色","直接包含"]} render={item=><Space><span>{item.title}</span><Tag>{item.description}</Tag></Space>} listStyle={{width:"calc(50% - 24px)",height:250}}/><Card size="small" title="最终有效权限"><Flex wrap gap={6}>{effective.map(r=><Tag key={r.id} color={assigned.includes(r.id)?"blue":"purple"}>{value(r,name)}{!assigned.includes(r.id)&&" · 继承"}</Tag>)}</Flex></Card><Button type="primary" icon={<SaveOutlined/>} disabled={!valid} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,roleIds:assigned,operation:"saveCompositeRole",targets:targets(p)})}>保存复合角色</Button></Flex>)};

export const HttpRequestWorkbenchRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),key=field(p,"headerNameFieldRef"),val=field(p,"headerValueFieldRef"),[method,setMethod]=React.useState(String(p.block.props?.method??"POST")),[url,setUrl]=React.useState(String(p.block.props?.url??"https://api.example.com/orders")),[body,setBody]=React.useState(String(p.block.props?.body??'{"limit":20}')),[sent,setSent]=React.useState(true),[loading,setLoading]=React.useState(false);if(!b||!key||!val)return missing(p,"http-request-workbench","HTTP 请求调试台");const valid=httpRequestCanSend(method,url),send=()=>{setLoading(true);setSent(false);setTimeout(()=>{setLoading(false);setSent(true)},250);p.onAction?.("submitRequest",{entityRef:b.entityRef,method,url,headers:Object.fromEntries(b.rows.map(r=>[value(r,key),value(r,val)])),body,operation:"sendHttpRequest",targets:targets(p)})};return shell(p,"http-request-workbench","HTTP 请求调试台",<Flex vertical gap={10}><Space.Compact block><Select value={method} onChange={setMethod} options={["GET","POST","PUT","PATCH","DELETE"].map(x=>({label:x,value:x}))} style={{width:110}}/><Input value={url} onChange={e=>setUrl(e.target.value)} status={url&&!valid?"error":undefined}/><Button type="primary" icon={<SendOutlined/>} loading={loading} disabled={!valid} onClick={send}>发送</Button></Space.Compact><Tabs defaultActiveKey="headers" items={[{key:"headers",label:`请求头 ${b.rows.length}`,children:<List size="small" dataSource={b.rows} renderItem={r=><List.Item><Space.Compact block><Input value={value(r,key)}/><Input.Password value={value(r,val)} visibilityToggle={false}/></Space.Compact></List.Item>}/>},{key:"body",label:"请求体",children:<Input.TextArea rows={6} value={body} onChange={e=>setBody(e.target.value)}/>},{key:"response",label:<Badge dot={sent}>响应</Badge>,children:sent?<Flex vertical gap={8}><Descriptions size="small" column={3} items={[{key:"status",label:"状态",children:<Tag color="success">200 OK</Tag>},{key:"time",label:"耗时",children:"184 ms"},{key:"size",label:"大小",children:"1.2 KB"}]}/><Typography.Paragraph code copyable style={{whiteSpace:"pre-wrap"}}>{'{"items":[{"id":"WB-2048","status":"paid"}],"next":null}'}</Typography.Paragraph></Flex>:<Empty description="发送请求后查看响应"/>}]} /></Flex>)};

export const BomAssemblyTreeEditorRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),name=field(p,"partNameFieldRef"),parent=field(p,"parentPartFieldRef"),qty=field(p,"quantityFieldRef"),cost=field(p,"unitCostFieldRef"),[drafts,setDrafts]=React.useState<Record<string,number>>({}),[selectedId,setSelectedId]=React.useState(b?.rows[0]?.id??"");if(!b||!name||!parent||!qty||!cost)return missing(p,"bom-assembly-tree-editor","BOM 装配树编辑器");const q=(r:Row)=>drafts[r.id]??numeric(r,qty,1),roots=b.rows.filter(r=>!value(r,parent)),children=(id:string)=>b.rows.filter(r=>value(r,parent)===id),node=(r:Row):any=>({key:r.id,title:<Space><span>{value(r,name)}</span><Tag>{q(r)} 件</Tag><Typography.Text type="secondary">¥{(q(r)*numeric(r,cost)).toFixed(0)}</Typography.Text></Space>,children:children(r.id).map(node)}),selected=b.rows.find(r=>r.id===selectedId)??b.rows[0],total=b.rows.reduce((s,r)=>s+q(r)*numeric(r,cost),0),valid=bomCanSave(b.rows.map(q));return shell(p,"bom-assembly-tree-editor","BOM 装配树编辑器",<div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 220px",gap:12}}><Card size="small" title="装配层级"><Tree showLine defaultExpandAll selectedKeys={[selected.id]} onSelect={keys=>keys[0]&&setSelectedId(String(keys[0]))} treeData={roots.map(node)}/></Card><Card size="small" title="物料检查器"><Flex vertical gap={12}><Typography.Title level={5}>{value(selected,name)}</Typography.Title><Space.Compact block><Button disabled>数量</Button><InputNumber min={0.01} value={q(selected)} onChange={v=>setDrafts(d=>({...d,[selected.id]:Number(v??0)}))} style={{width:"100%"}}/></Space.Compact><Statistic title="单位成本" value={numeric(selected,cost)} prefix="¥" precision={2}/><Statistic title="BOM 总成本" value={total} prefix="¥" precision={2}/><Progress percent={Math.min(100,Math.round(total/20))} showInfo={false}/><Button type="primary" disabled={!valid} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,quantities:Object.fromEntries(b.rows.map(r=>[r.id,q(r)])),operation:"saveBomAssembly",targets:targets(p)})}>保存装配树</Button></Flex></Card></div>)};

export const AlertThresholdBandEditorRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),label=field(p,"seriesLabelFieldRef"),current=field(p,"currentValueFieldRef"),[warning,setWarning]=React.useState(Number(p.block.props?.warning??60)),[critical,setCritical]=React.useState(Number(p.block.props?.critical??85));if(!b||!label||!current)return missing(p,"alert-threshold-band-editor","告警阈值带编辑器");const max=Math.max(100,...b.rows.map(r=>numeric(r,current))),valid=thresholdsValid(warning,critical);return shell(p,"alert-threshold-band-editor","告警阈值带编辑器",<Flex vertical gap={14}><div style={{position:"relative",height:190,borderLeft:"1px solid #d9d9d9",borderBottom:"1px solid #d9d9d9",background:`linear-gradient(90deg,#f6ffed 0 ${warning}%,#fffbe6 ${warning}% ${critical}%,#fff1f0 ${critical}% 100%)`}}>{b.rows.map((r,i)=>{const x=numeric(r,current)/max*100;return <div key={r.id} style={{position:"absolute",left:`${x}%`,top:30+i*46,transform:"translateX(-50%)",textAlign:"center"}}><Badge status={numeric(r,current)>=critical?"error":numeric(r,current)>=warning?"warning":"success"}/><div style={{height:22,borderLeft:"2px solid #1677ff"}}/><Tag>{value(r,label)} {numeric(r,current)}</Tag></div>})}<div style={{position:"absolute",left:`${warning}%`,insetBlock:0,borderLeft:"2px dashed #faad14"}}/><div style={{position:"absolute",left:`${critical}%`,insetBlock:0,borderLeft:"2px dashed #ff4d4f"}}/></div><Slider range min={0} max={100} value={[warning,critical]} onChange={v=>{setWarning(v[0]);setCritical(v[1])}}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Space.Compact block><Button disabled>警告</Button><InputNumber value={warning} onChange={v=>setWarning(Number(v??0))}/></Space.Compact><Space.Compact block><Button disabled>严重</Button><InputNumber value={critical} onChange={v=>setCritical(Number(v??0))}/></Space.Compact></div><Alert type={valid?"success":"error"} showIcon message={valid?"阈值顺序有效":"警告阈值必须小于严重阈值"}/><Button type="primary" disabled={!valid} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,warning,critical,operation:"saveAlertThresholds",targets:targets(p)})}>保存阈值</Button></Flex>)};

export const MediaTrimTimelineRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),name=field(p,"mediaNameFieldRef"),durationRef=field(p,"durationFieldRef"),marker=field(p,"markerOffsetFieldRef"),markerLabel=field(p,"markerLabelFieldRef"),duration=Math.max(...(b?.rows.map(r=>numeric(r,durationRef))??[60]),1),[range,setRange]=React.useState<[number,number]>([8,Math.min(52,duration)]),[playing,setPlaying]=React.useState(false);if(!b||!name||!durationRef||!marker)return missing(p,"media-trim-timeline","媒体区间裁剪器");const valid=trimRangeValid(range[0],range[1],duration);return shell(p,"media-trim-timeline","媒体区间裁剪器",<Flex vertical gap={12}><div style={{height:230,display:"grid",placeItems:"center",borderRadius:6,background:"#111",color:"white"}}><Flex vertical align="center" gap={10}><PlayCircleOutlined style={{fontSize:54,opacity:.8}}/><Typography.Text style={{color:"white"}}>{value(b.rows[0],name)}</Typography.Text><Tag color="blue">预览 {range[0].toFixed(1)}s - {range[1].toFixed(1)}s</Tag></Flex></div><div style={{position:"relative",paddingTop:22}}><div style={{display:"grid",gridTemplateColumns:"repeat(24,1fr)",gap:2}}>{Array.from({length:24},(_,i)=><div key={i} style={{height:32+Math.sin(i)*12,alignSelf:"center",background:i/23*duration>=range[0]&&i/23*duration<=range[1]?"#1677ff":"#d9d9d9",borderRadius:2}}/>)}</div>{b.rows.map(r=><Tag key={r.id} color="orange" style={{position:"absolute",left:`${numeric(r,marker)/duration*100}%`,top:0,transform:"translateX(-50%)"}}>{markerLabel?value(r,markerLabel):numeric(r,marker)}</Tag>)}</div><Slider range min={0} max={duration} step={0.1} value={range} onChange={v=>setRange(v as [number,number])}/><Flex justify="space-between" align="center"><Space><Button icon={playing?<ClockCircleOutlined/>:<CaretRightOutlined/>} onClick={()=>setPlaying(x=>!x)}>{playing?"暂停":"预览"}</Button><span>成片 {(range[1]-range[0]).toFixed(1)} 秒</span></Space><Button type="primary" disabled={!valid} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,start:range[0],end:range[1],operation:"trimMedia",targets:targets(p)})}>应用裁剪</Button></Flex></Flex>)};

export const CronOccurrenceBuilderRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),label=field(p,"scheduleLabelFieldRef"),expressionRef=field(p,"cronExpressionFieldRef"),timezoneRef=field(p,"timezoneFieldRef"),[expression,setExpression]=React.useState(value(b?.rows[0]??({values:{}} as Row),expressionRef,"0 9 * * 1-5")),[enabled,setEnabled]=React.useState(true);if(!b||!label||!expressionRef)return missing(p,"cron-occurrence-builder","Cron 触发预览器");const valid=cronExpressionValid(expression),next=["2026-08-12 09:00","2026-08-13 09:00","2026-08-14 09:00","2026-08-17 09:00"];return shell(p,"cron-occurrence-builder","Cron 触发预览器",<div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 220px",gap:12}}><Card size="small" title="触发规则"><Flex vertical gap={12}><Segmented block options={[{label:"工作日 9 点",value:"0 9 * * 1-5"},{label:"每小时",value:"0 * * * *"},{label:"自定义",value:"custom"}]} onChange={v=>v!=="custom"&&setExpression(String(v))}/><Input value={expression} onChange={e=>setExpression(e.target.value)} status={expression&&!valid?"error":undefined} prefix={<ClockCircleOutlined/>}/><Collapse items={[{key:"fields",label:"表达式字段",children:<div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:6}}>{["分钟","小时","日期","月份","星期"].map((x,i)=><Card size="small" key={x}><Typography.Text type="secondary">{x}</Typography.Text><div>{expression.split(/\s+/)[i]??"-"}</div></Card>)}</div>}]} /><Flex justify="space-between"><span>启用计划</span><Switch checked={enabled} onChange={setEnabled}/></Flex><Button type="primary" icon={<SaveOutlined/>} disabled={!valid} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,expression,enabled,operation:"saveCronSchedule",targets:targets(p)})}>保存触发规则</Button></Flex></Card><Card size="small" title="未来触发"><Tag color={valid?"success":"error"}>{timezoneRef?value(b.rows[0],timezoneRef):"Asia/Shanghai"}</Tag><Timeline style={{marginTop:16}} items={next.map((time,i)=>({color:i?"gray":"blue",children:time}))}/><Alert type={valid?"info":"error"} message={valid?value(b.rows[0],label):"表达式必须是五段"}/></Card></div>)};

export const INDEPENDENT_STRUCTURE_BATCH6_LABELS:Record<string,string>={CompositeRoleBuilder:"复合角色构建器",HttpRequestWorkbench:"HTTP 请求调试台",BomAssemblyTreeEditor:"BOM 装配树编辑器",AlertThresholdBandEditor:"告警阈值带编辑器",MediaTrimTimeline:"媒体区间裁剪器",CronOccurrenceBuilder:"Cron 触发预览器"};
