import React from "react";
import dayjs from "dayjs";
import { Alert, Button, Calendar, Card, Drawer, Empty, Flex, List, Progress, Space, Tag, Typography } from "antd";
import type { ExperienceBlockRenderer, ExperienceBlockRendererProps } from "./block-registry";

type Row = NonNullable<ExperienceBlockRendererProps["entityRows"]>[string][number];
const ref = (p: ExperienceBlockRendererProps, key: string) => { const v = (p.block.binding as Record<string, unknown> | undefined)?.[key]; return typeof v === "string" && v ? v : undefined; };
const bound = (p: ExperienceBlockRendererProps) => { const entityRef = ref(p, "entityRef"); const rows = entityRef ? p.entityRows?.[entityRef] : undefined; return entityRef && rows ? { entityRef, rows } : undefined; };
const targetIds = (p: ExperienceBlockRendererProps) => { const v = (p.block.binding as Record<string, unknown> | undefined)?.targets; return Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : []; };
function Shell({ p, testid, children }: { p: ExperienceBlockRendererProps; testid: string; children: React.ReactNode }) { const title = String(p.block.props?.title ?? ""); return p.block.props?.surface === "plain" ? <section data-testid={testid}>{title && <Typography.Title level={5}>{title}</Typography.Title>}{children}</section> : <Card title={title || undefined} data-testid={testid}>{children}</Card>; }
const Missing = ({ text }: { text: string }) => <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={text} />;

type CalendarConfig = { testid: string; secondary: "memberFieldRef" | "resourceFieldRef"; extra?: "participantFieldRef" | "locationFieldRef" | "typeFieldRef"; create?: boolean; edit?: boolean };
function ScheduleCalendar(p: ExperienceBlockRendererProps, config: CalendarConfig) {
  const data = bound(p), title = ref(p, "titleFieldRef"), start = ref(p, "startFieldRef"), end = ref(p, "endFieldRef"), status = ref(p, "statusFieldRef"), secondary = ref(p, config.secondary), extra = config.extra ? ref(p, config.extra) : undefined;
  const [date, setDate] = React.useState(dayjs());
  if (!data || !title || !start || !secondary) return <Shell p={p} testid={config.testid}><Missing text="排期尚未绑定标题、日期和资源字段" /></Shell>;
  const key = date.format("YYYY-MM-DD");
  const inDate = (row: Row, value: dayjs.Dayjs) => { const from = dayjs(String(row.values[start] ?? "")); const to = end ? dayjs(String(row.values[end] ?? "")) : from; return from.isValid() && !value.endOf("day").isBefore(from) && !value.startOf("day").isAfter(to.isValid() ? to : from); };
  const rows = data.rows.filter(row => inDate(row, date));
  return <Shell p={p} testid={config.testid}><Flex gap={16} wrap align="flex-start"><div style={{ flex: "1 1 420px", minWidth: 280 }}><Calendar fullscreen={false} value={date} onSelect={setDate} cellRender={current => { const count = data.rows.filter(row => inDate(row, current)).length; return count ? <Tag color="blue">{count}</Tag> : null; }} /></div><div style={{ flex: "1 1 300px", minWidth: 260 }}><Flex justify="space-between" align="center"><Typography.Text strong>{key} 安排</Typography.Text>{config.create && <Button size="small" type="primary" onClick={() => p.onAction?.("createRequest", { entityRef: data.entityRef, date: key })}>新建</Button>}</Flex>{rows.length === 0 ? <Missing text="当前日期没有安排" /> : <List dataSource={rows} renderItem={row => <List.Item onClick={() => p.onAction?.("itemSelect", { entityRef: data.entityRef, rowId: row.id })} actions={config.edit ? [<Button key="edit" type="link" onClick={event => { event.stopPropagation(); p.onAction?.("editRequest", { entityRef: data.entityRef, rowId: row.id }); }}>调整</Button>] : undefined}><List.Item.Meta title={String(row.values[title] ?? "未命名安排")} description={`${String(row.values[secondary] ?? "未分配")}${extra ? ` · ${String(row.values[extra] ?? "")}` : ""} · ${String(row.values[start] ?? "")}${end ? ` - ${String(row.values[end] ?? "")}` : ""}`} />{status && <Tag>{String(row.values[status] ?? "")}</Tag>}</List.Item>} />}</div></Flex></Shell>;
}

export const OnCallScheduleCalendarRenderer: ExperienceBlockRenderer = p => ScheduleCalendar(p, { testid: "on-call-schedule-calendar", secondary: "memberFieldRef", extra: "typeFieldRef", edit: true });

export const AppointmentWaitlistPanelRenderer: ExperienceBlockRenderer = p => { const data = bound(p), title = ref(p, "titleFieldRef"), member = ref(p, "memberFieldRef"), position = ref(p, "positionFieldRef"), status = ref(p, "statusFieldRef"); if (!data || !title || !member || !position || !status) return <Shell p={p} testid="appointment-waitlist-panel"><Missing text="候补队列尚未绑定顺位和状态" /></Shell>; const rows = [...data.rows].sort((a,b) => Number(a.values[position])-Number(b.values[position])); return <Shell p={p} testid="appointment-waitlist-panel">{rows.length === 0 ? <Missing text="当前没有候补预约" /> : <List dataSource={rows} renderItem={row => <List.Item actions={[<Button key="select" onClick={() => p.onAction?.("itemSelect", {entityRef:data.entityRef,rowId:row.id})}>查看</Button>, <Button key="confirm" type="primary" disabled={String(row.values[status]).toLowerCase() !== "waiting"} onClick={() => p.onAction?.("submitRequest", {entityRef:data.entityRef,rowId:row.id,operation:"confirmWaitlistSeat",targets:targetIds(p)})}>确认席位</Button>]}><List.Item.Meta title={`#${String(row.values[position])} ${String(row.values[member])}`} description={String(row.values[title])} /><Tag>{String(row.values[status])}</Tag></List.Item>} />}</Shell>; };

export const AvailabilityOverridePanelRenderer: ExperienceBlockRenderer = p => { const data = bound(p), date = ref(p,"dateFieldRef"), start = ref(p,"startTimeFieldRef"), end = ref(p,"endTimeFieldRef"), enabled = ref(p,"enabledFieldRef"), timezone = ref(p,"timezoneFieldRef"); if(!data||!date||!start||!end||!enabled) return <Shell p={p} testid="availability-override-panel"><Missing text="可用时间覆盖尚未绑定日期和窗口" /></Shell>; return <Shell p={p} testid="availability-override-panel"><Alert message={`时区：${String(p.block.props?.timezone ?? "按规则时区")}`} style={{marginBottom:12}} /><List dataSource={data.rows} locale={{emptyText:"还没有日期覆盖"}} renderItem={row => <List.Item actions={[<Button key="edit" onClick={() => p.onAction?.("editRequest",{entityRef:data.entityRef,rowId:row.id})}>编辑</Button>,<Button key="save" type="primary" onClick={() => p.onAction?.("submitRequest",{entityRef:data.entityRef,rowId:row.id,operation:"saveAvailabilityOverride",targets:targetIds(p)})}>保存</Button>]}><List.Item.Meta title={String(row.values[date])} description={`${String(row.values[start])} - ${String(row.values[end])}${timezone?` · ${String(row.values[timezone]??"")}`:""}`} /><Tag color={String(row.values[enabled]).toLowerCase()==="false"?"default":"success"}>{String(row.values[enabled]).toLowerCase()==="false"?"不可用":"可用"}</Tag></List.Item>} /></Shell>; };

export const TimezoneOverlapPanelRenderer: ExperienceBlockRenderer = p => { const data=bound(p), member=ref(p,"memberFieldRef"), timezone=ref(p,"timezoneFieldRef"), start=ref(p,"startTimeFieldRef"), end=ref(p,"endTimeFieldRef"), status=ref(p,"statusFieldRef"); if(!data||!member||!timezone||!start||!end) return <Shell p={p} testid="timezone-overlap-panel"><Missing text="时区重叠尚未绑定成员与时间窗口" /></Shell>; return <Shell p={p} testid="timezone-overlap-panel">{data.rows.length===0?<Missing text="当前没有可比较的时区窗口"/>:<List dataSource={data.rows} renderItem={row=><List.Item onClick={()=>p.onAction?.("itemSelect",{entityRef:data.entityRef,rowId:row.id})}><List.Item.Meta title={String(row.values[member])} description={`${String(row.values[start])} - ${String(row.values[end])}`} /><Space><Tag color="blue">{String(row.values[timezone])}</Tag>{status&&<Tag>{String(row.values[status]??"")}</Tag>}</Space></List.Item>}/>}</Shell>; };

export const SchedulePublishBarRenderer: ExperienceBlockRenderer = p => { const data=bound(p), status=ref(p,"statusFieldRef"), dirty=ref(p,"dirtyFieldRef"), published=ref(p,"publishedAtFieldRef"), row=data?.rows[0]; if(!data||!status||!dirty||!row) return <Shell p={p} testid="schedule-publish-bar"><Missing text="发布栏尚未绑定状态和变更字段" /></Shell>; const state=String(row.values[status]).toLowerCase(), changed=[true,"true","dirty","changed"].includes(row.values[dirty] as never), publishing=["publishing","saving"].includes(state); return <Shell p={p} testid="schedule-publish-bar"><Flex justify="space-between" align="center" gap={12}><div><Typography.Text strong>{changed?"有未保存变更":state==="published"?"已发布":"草稿"}</Typography.Text>{published&&<div style={{color:"#999"}}>最近发布：{String(row.values[published]??"-")}</div>}</div><Space><Button disabled={!changed||publishing} onClick={()=>p.onAction?.("actionTrigger",{entityRef:data.entityRef,rowId:row.id,operation:"saveSchedule",targets:targetIds(p)})}>保存</Button><Button type="primary" loading={publishing} disabled={changed||publishing} onClick={()=>p.onAction?.("submitRequest",{entityRef:data.entityRef,rowId:row.id,operation:"publishSchedule",targets:targetIds(p)})}>发布</Button></Space></Flex></Shell>; };

export const RescheduleRequestDrawerRenderer: ExperienceBlockRenderer = p => { const data=bound(p), title=ref(p,"titleFieldRef"), start=ref(p,"startFieldRef"), requested=ref(p,"requestedStartFieldRef"), status=ref(p,"statusFieldRef"), end=ref(p,"endFieldRef"), requestedEnd=ref(p,"requestedEndFieldRef"), reason=ref(p,"reasonFieldRef"), [open,setOpen]=React.useState(false), [active,setActive]=React.useState<Row|undefined>(); if(!data||!title||!start||!requested||!status) return <Shell p={p} testid="reschedule-request-drawer"><Missing text="改期请求尚未绑定原时间和建议时间" /></Shell>; const rows=data.rows.filter(row=>["pending","requested","waiting"].includes(String(row.values[status]).toLowerCase())); return <Shell p={p} testid="reschedule-request-drawer"><Button block onClick={()=>setOpen(true)}>查看改期请求 {rows.length}</Button><Drawer open={open} onClose={()=>setOpen(false)} title="改期请求"><List dataSource={rows} locale={{emptyText:"当前没有待处理改期"}} renderItem={row=><List.Item onClick={()=>{setActive(row);p.onAction?.("itemSelect",{entityRef:data.entityRef,rowId:row.id})}}><List.Item.Meta title={String(row.values[title])} description={`${String(row.values[start])}${end?` - ${String(row.values[end]??"")}`:""} → ${String(row.values[requested])}${requestedEnd?` - ${String(row.values[requestedEnd]??"")}`:""}${reason?` · ${String(row.values[reason]??"")}`:""}`} /></List.Item>} />{active&&<Flex gap={8} style={{marginTop:16}}><Button danger block onClick={()=>p.onAction?.("submitRequest",{entityRef:data.entityRef,rowId:active.id,operation:"rejectReschedule",targets:targetIds(p)})}>拒绝</Button><Button type="primary" block onClick={()=>p.onAction?.("submitRequest",{entityRef:data.entityRef,rowId:active.id,operation:"acceptReschedule",targets:targetIds(p)})}>接受改期</Button></Flex>}</Drawer></Shell>; };
